### ISSUE TITLE
Update to 0.4.9 from 0.3.0?

### ISSUE THREAD

**Issue by misto** [webjars/c3#1]
I noticed that the last released version is 0.4.9, whereas the webjar is still on 0.3. To update it, can we jump directly to 0.4.9 or do we also need to make the intermediate releases available?

**Comment by jamesward** [comment]
WebJars versions are on-demand so we can just skip to 0.4.9.  This will be released shortly.

**Comment by misto** [comment]
Ok, thanks! :-)
